export const uiActionTypes = {
    START_ACTION: "START_ACTION",
    STOP_ACTION: "STOP_ACTION",
    REFRESH_ACTION_START: "REFRESH_ACTION_START",
    REFRESH_ACTION_STOP: "REFRESH_ACTION_STOP",
    SET_SIDEBAR_MINIMIZED: "SET_SIDEBAR_MINIMIZED",
    SET_ACTIVE_COMPONENT: "SET_ACTIVE_COMPONENT",
    SET_ACTIVE_ITEM: "SET_ACTIVE_ITEM"
}

export const authActionTypes = {
    SIGN_IN: "SIGN_IN",
    SIGN_IN_SUCCES: "SIGN_IN_SUCCES",
    SIGN_IN_FAILED: "SIGN_IN_FAILED",
    SIGN_OUT: "SIGN_OUT",
    RESET: "RESET",
    RESET_SUCCES: "RESET_SUCCES",
    RESET_FAILED: "RESET_FAILED",
    SET_NEW_LOGIN: "SET_NEW_LOGIN"
}

